// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEolAEQ6Nq475GtM8gCdTuJO-Gd-Uy-0o',
    appId: '1:58254269090:web:dbdcd6525f7108d6ce55fb',
    messagingSenderId: '58254269090',
    projectId: 'rondalarmecamerasflutter',
    authDomain: 'rondalarmecamerasflutter.firebaseapp.com',
    storageBucket: 'rondalarmecamerasflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj0i6LMdgp6XiTy6OjZjZC_2iWWivr9Do',
    appId: '1:58254269090:android:652eccbc4c37e1c5ce55fb',
    messagingSenderId: '58254269090',
    projectId: 'rondalarmecamerasflutter',
    storageBucket: 'rondalarmecamerasflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq3O3zA3fGpWfdfNTUrd8dIPPF7RNnI94',
    appId: '1:58254269090:ios:a796319264c7943ace55fb',
    messagingSenderId: '58254269090',
    projectId: 'rondalarmecamerasflutter',
    storageBucket: 'rondalarmecamerasflutter.firebasestorage.app',
    iosBundleId: 'com.example.rondalarmeCamerasFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq3O3zA3fGpWfdfNTUrd8dIPPF7RNnI94',
    appId: '1:58254269090:ios:a796319264c7943ace55fb',
    messagingSenderId: '58254269090',
    projectId: 'rondalarmecamerasflutter',
    storageBucket: 'rondalarmecamerasflutter.firebasestorage.app',
    iosBundleId: 'com.example.rondalarmeCamerasFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEolAEQ6Nq475GtM8gCdTuJO-Gd-Uy-0o',
    appId: '1:58254269090:web:362fe08e8578e8cece55fb',
    messagingSenderId: '58254269090',
    projectId: 'rondalarmecamerasflutter',
    authDomain: 'rondalarmecamerasflutter.firebaseapp.com',
    storageBucket: 'rondalarmecamerasflutter.firebasestorage.app',
  );
}
